import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import ModelName from "../ModelName";
import { accessTypeLabel, MODEL_KIND_LABELS } from "../../lib/modelCatalog";
import { formatContextLength, formatModelTitle, formatPerMTokenPrice, formatReleasedDate, } from "../../lib/modelCatalogFormat";
export default function ModelsBrowseView({ models, selectedIds, onToggleSelect, onToggleEnabled, onEditAccess, }) {
    return (_jsx("div", { className: "models-browse-list", children: models.map((m) => {
            const kinds = m.kinds?.length ? m.kinds : [];
            return (_jsxs("article", { className: `models-browse-card card${m.enabled ? "" : " models-browse-card--off"}`, children: [_jsxs("div", { className: "models-browse-card__top", children: [_jsx("label", { className: "models-browse-card__check", children: _jsx("input", { type: "checkbox", checked: selectedIds.includes(m.id), onChange: () => onToggleSelect(m.id), "aria-label": `Select ${m.external_id}` }) }), _jsxs("div", { className: "models-browse-card__head", children: [_jsx("h3", { className: "models-browse-card__title", children: _jsx(ModelName, { modelId: m.external_id, label: formatModelTitle(m), provider: m.provider_author, size: 18 }) }), kinds.length > 0 ? (_jsx("div", { className: "models-browse-card__tags", children: kinds.map((k) => (_jsx("span", { className: "models-browse-card__tag", children: MODEL_KIND_LABELS[k] }, k))) })) : null] }), _jsxs("div", { className: "model-onoff-cell", children: [_jsx("button", { type: "button", className: `btn btn-sm btn-ghost model-access-btn${(m.access_type || "public") === "private" ? " model-access-btn--private" : ""}`, onClick: () => onEditAccess(m.id), children: accessTypeLabel(m) }), _jsx("button", { type: "button", className: `btn btn-sm model-toggle-btn${m.enabled ? " model-toggle-btn--on" : ""}`, onClick: () => onToggleEnabled(m.id, m.enabled), children: m.enabled ? "ON" : "OFF" }), m.admin_disabled ? (_jsx("span", { className: "model-admin-off-badge", title: "Disabled by admin \u2014 sync will not re-enable", children: "Admin off" })) : null, m.is_system_default ? (_jsx("span", { className: "model-default-badge", title: "System default for new chats. Does not change users who already picked their own.", children: "Default" })) : null] })] }), m.description ? (_jsx("p", { className: "models-browse-card__desc", children: m.description })) : (_jsx("p", { className: "models-browse-card__desc muted-text", children: "No description from provider yet. Re-sync connection." })), _jsxs("footer", { className: "models-browse-card__meta", children: [_jsxs("span", { children: ["by ", _jsx("span", { className: "models-browse-card__provider", children: m.provider_author || "—" })] }), m.released_at ? _jsx("span", { children: formatReleasedDate(m.released_at) }) : null, m.context_length != null ? _jsx("span", { children: formatContextLength(m.context_length) }) : null, m.input_cost_per_1k != null ? (_jsx("span", { children: formatPerMTokenPrice(m.input_cost_per_1k, "input") })) : null, m.output_cost_per_1k != null ? (_jsx("span", { children: formatPerMTokenPrice(m.output_cost_per_1k, "output") })) : null] })] }, m.id));
        }) }));
}
