"""ORM models — import all for Alembic metadata."""

from app.models.agent import (
    Agent,
    AgentAccessAssignment,
    AgentAuditEvent,
    AgentHandoffEvent,
    AgentKnowledgeBinding,
    AgentVersion,
)
from app.models.agent_runtime import (
    AgentCitation,
    AgentEscalationCase,
    AgentRetrievalTrace,
    AgentRun,
    AgentToolRun,
)
from app.models.agent_tool import (
    AgentTool,
    AgentToolAuditEvent,
    AgentToolVersion,
)
from app.models.api_key import (
    AlphaRouterApiKey,
    AlphaRouterApiKeyAuditLog,
    UserApiKey,
    alpha_router_api_key_connections,
    alpha_router_api_key_models,
)
from app.models.auth_provider import AuthProviderConfig
from app.models.budget import BudgetPlan, PlanAssignment
from app.models.budget_reservation import BudgetReservation
from app.models.chat import (
    ChatFolder,
    ChatMessage,
    ChatMessageFeedback,
    ChatSession,
    UserChatPrefs,
    UserMemory,
    UserMemoryEvent,
    UserMemoryJob,
    UserMemorySuppression,
)
from app.models.chat_tool import ChatToolAccessAssignment, ChatToolPolicy
from app.models.connection import Connection, ConnectionAuditLog
from app.models.cost_accounting import (
    CostLineItem,
    LedgerEntry,
    PricingSnapshot,
    ReconciliationRun,
    UsageEvent,
    UsageOperation,
)
from app.models.evaluation import (
    EvaluationCase,
    EvaluationDataset,
    EvaluationResult,
    EvaluationRun,
)
from app.models.governance import GovernanceAuditEvent
from app.models.knowledge import (
    ConnectorSyncRun,
    DeletionTombstone,
    IngestionJob,
    KnowledgeAuditEvent,
    KnowledgeBase,
    KnowledgeBaseAccessAssignment,
    KnowledgeChunk,
    KnowledgeConnector,
    KnowledgeDocument,
    KnowledgeDocumentAccessAssignment,
    KnowledgeDocumentVersion,
    KnowledgeIndexVersion,
    KnowledgeRelease,
    KnowledgeReleaseDocument,
    LegalHold,
    OutboxEvent,
)
from app.models.logging import ImageGenerationAttempt, RequestLog
from app.models.media import MediaAsset
from app.models.model_catalog import (
    AIModel,
    ModelAccessAssignment,
    ModelToolCompatibility,
    ModelToolCompatibilityEvent,
)
from app.models.project import (
    Project,
    ProjectAuditEvent,
    ProjectChatComposerPref,
    ProjectChatPin,
    ProjectConfigVersion,
    ProjectInvitation,
    ProjectMediaAsset,
    ProjectMember,
    ProjectMemory,
    ProjectMemoryEvent,
    ProjectMemoryGrant,
    ProjectMemoryJob,
    ProjectMemorySuppression,
    ProjectResource,
    ProjectRoomHandoff,
    ProjectUserPref,
)
from app.models.security import AdminIpAllowlistEntry, SecurityAuditEvent, TlsCertificate
from app.models.system import (
    ReportSchedule,
    SmtpSettings,
    SystemMetricSnapshot,
    SystemSetting,
)
from app.models.user import User, UserGroup, UserRoleAssignment, user_group_members
from app.models.user_media_prefs import UserMediaPreferences
from app.models.video import VideoGenerationJob

__all__ = [
    "AIModel",
    "Agent",
    "AgentAccessAssignment",
    "AgentAuditEvent",
    "AgentCitation",
    "AgentEscalationCase",
    "AgentHandoffEvent",
    "AgentKnowledgeBinding",
    "AgentRetrievalTrace",
    "AgentRun",
    "AgentTool",
    "AgentToolAuditEvent",
    "AgentToolRun",
    "AgentToolVersion",
    "AgentVersion",
    "AlphaRouterApiKey",
    "AlphaRouterApiKeyAuditLog",
    "alpha_router_api_key_connections",
    "alpha_router_api_key_models",
    "AuthProviderConfig",
    "BudgetPlan",
    "BudgetReservation",
    "ChatFolder",
    "ChatMessage",
    "ChatMessageFeedback",
    "ChatSession",
    "ChatToolAccessAssignment",
    "ChatToolPolicy",
    "Connection",
    "ConnectionAuditLog",
    "ConnectorSyncRun",
    "CostLineItem",
    "DeletionTombstone",
    "EvaluationCase",
    "EvaluationDataset",
    "EvaluationResult",
    "EvaluationRun",
    "GovernanceAuditEvent",
    "ImageGenerationAttempt",
    "IngestionJob",
    "KnowledgeAuditEvent",
    "KnowledgeBase",
    "KnowledgeBaseAccessAssignment",
    "KnowledgeChunk",
    "KnowledgeConnector",
    "KnowledgeDocument",
    "KnowledgeDocumentAccessAssignment",
    "KnowledgeDocumentVersion",
    "KnowledgeIndexVersion",
    "KnowledgeRelease",
    "KnowledgeReleaseDocument",
    "LedgerEntry",
    "LegalHold",
    "MediaAsset",
    "ModelAccessAssignment",
    "ModelToolCompatibility",
    "ModelToolCompatibilityEvent",
    "OutboxEvent",
    "PlanAssignment",
    "PricingSnapshot",
    "Project",
    "ProjectAuditEvent",
    "ProjectChatComposerPref",
    "ProjectChatPin",
    "ProjectConfigVersion",
    "ProjectInvitation",
    "ProjectMediaAsset",
    "ProjectMember",
    "ProjectMemory",
    "ProjectMemoryEvent",
    "ProjectMemoryGrant",
    "ProjectMemoryJob",
    "ProjectMemorySuppression",
    "ProjectResource",
    "ProjectRoomHandoff",
    "ProjectUserPref",
    "ReconciliationRun",
    "ReportSchedule",
    "RequestLog",
    "SecurityAuditEvent",
    "SmtpSettings",
    "SystemMetricSnapshot",
    "SystemSetting",
    "TlsCertificate",
    "AdminIpAllowlistEntry",
    "UsageEvent",
    "UsageOperation",
    "User",
    "UserApiKey",
    "UserChatPrefs",
    "UserGroup",
    "UserMemory",
    "UserMemoryEvent",
    "UserMemoryJob",
    "UserMemorySuppression",
    "UserRoleAssignment",
    "UserMediaPreferences",
    "VideoGenerationJob",
    "user_group_members",
    "alpha_router_api_key_connections",
    "alpha_router_api_key_models",
]
