"""Persistent media assets generated by users."""

import datetime

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text

from app.database import Base


class MediaAsset(Base):
    __tablename__ = "media_assets"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)
    kind = Column(String(32), nullable=False, default="image")  # image | document | other
    mime_type = Column(String(128), nullable=False, default="application/octet-stream")
    file_name = Column(String(255), nullable=False)
    storage_path = Column(Text, nullable=False)  # object key under MinIO/S3 (cdn/u/{user_id}/…)
    content_hash = Column(String(64), nullable=True, index=True)  # SHA-256 hex; deduped per user
    size_bytes = Column(Integer, nullable=False, default=0)
    source_model = Column(String(512), nullable=True)
    source_prompt = Column(Text, nullable=True)
    chat_session_id = Column(String(128), nullable=True)
    metadata_json = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
    expires_at = Column(DateTime, nullable=True)
