import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import Modal from "./Modal";
import ModelName from "./ModelName";
import { formatLocalDateTime } from "../lib/dateTime";
import { confidenceLabel, formatTokenCount, logIdentityLabel, money, } from "../lib/requestLogCostDetails";
export default function RequestLogCostDetailsModal({ open, log, details, loading, error, onClose, exportSlot, exportError, }) {
    const fmt = formatTokenCount;
    return (_jsx(Modal, { open: open, title: log ? `Cost details · #${log.id}` : "Cost details", onClose: onClose, panelClassName: "modal-panel--cost-details", children: log && (_jsxs("div", { className: "api-log-cost-details", children: [exportSlot ? _jsx("div", { className: "api-log-cost-details__actions", children: exportSlot }) : null, exportError ? _jsx("p", { className: "error", children: exportError }) : null, _jsxs("div", { className: "api-log-cost-details__summary", children: [_jsxs("div", { children: [_jsx("span", { className: "muted", children: "Time" }), _jsx("strong", { children: formatLocalDateTime(log.request_time) })] }), _jsxs("div", { children: [_jsx("span", { className: "muted", children: "User / API key" }), _jsx("strong", { children: logIdentityLabel(log) })] }), _jsxs("div", { children: [_jsx("span", { className: "muted", children: "Model" }), _jsx("strong", { children: _jsx(ModelName, { modelId: log.model_id, label: log.model_id, size: 14 }) })] }), _jsxs("div", { children: [_jsx("span", { className: "muted", children: "Logged cost" }), _jsx("strong", { children: money(log.total_cost_usd) })] }), _jsxs("div", { children: [_jsx("span", { className: "muted", children: "Quality" }), _jsx("strong", { children: _jsx("span", { className: `api-log-cost-quality api-log-cost-quality--${confidenceLabel(log.cost_confidence || "unknown", !!log.has_unpriced_usage).key}`, children: confidenceLabel(log.cost_confidence || "unknown", !!log.has_unpriced_usage)
                                            .label }) })] })] }), loading && _jsx("p", { className: "muted", children: "Loading cost ledger\u2026" }), error && _jsx("p", { className: "error", children: error }), !loading && !error && details?.legacy && (_jsxs("p", { className: "muted", children: ["This request was logged before the usage ledger. Only the summary total is available (", money(details.total_cost_usd ?? log.total_cost_usd), ")."] })), !loading && !error && details && !details.legacy && (_jsxs(_Fragment, { children: [details.operation && (_jsxs("div", { className: "api-log-cost-details__operation", children: [_jsx("h4", { children: "Operation" }), _jsxs("dl", { children: [_jsxs("div", { children: [_jsx("dt", { children: "Type" }), _jsx("dd", { children: details.operation.operation_type })] }), _jsxs("div", { children: [_jsx("dt", { children: "Status" }), _jsx("dd", { children: details.operation.status })] }), _jsxs("div", { children: [_jsx("dt", { children: "Total" }), _jsx("dd", { children: money(details.operation.total_cost_usd) })] }), _jsxs("div", { children: [_jsx("dt", { children: "Provider" }), _jsx("dd", { children: money(details.operation.provider_cost_usd) })] }), _jsxs("div", { children: [_jsx("dt", { children: "Calculated" }), _jsx("dd", { children: money(details.operation.calculated_cost_usd) })] }), _jsxs("div", { children: [_jsx("dt", { children: "Unpriced events" }), _jsx("dd", { children: details.operation.unpriced_event_count })] }), details.operation.reconciled_at && (_jsxs("div", { children: [_jsx("dt", { children: "Reconciled" }), _jsx("dd", { children: formatLocalDateTime(details.operation.reconciled_at) })] }))] })] })), _jsxs("div", { className: "api-log-cost-details__events", children: [_jsxs("h4", { children: ["Upstream attempts (", details.events.length, ")"] }), details.events.length === 0 && (_jsx("p", { className: "muted", children: "No usage events were recorded for this operation." })), details.events.map((event) => {
                                    const quality = confidenceLabel(event.cost_confidence || "unknown");
                                    return (_jsxs("article", { className: "api-log-cost-event", children: [_jsxs("header", { children: [_jsxs("div", { children: [_jsxs("strong", { children: ["Attempt ", event.attempt_index, " \u00B7 ", event.operation_name || event.service_type] }), _jsxs("span", { className: "muted", children: [event.provider_type, event.model_id ? ` · ${event.model_id}` : "", ` · ${event.status}`] })] }), _jsx("span", { className: `api-log-cost-quality api-log-cost-quality--${quality.key}`, children: quality.label })] }), _jsxs("dl", { children: [_jsxs("div", { children: [_jsx("dt", { children: "Final" }), _jsx("dd", { children: money(event.final_cost_usd) })] }), _jsxs("div", { children: [_jsx("dt", { children: "Provider" }), _jsx("dd", { children: money(event.provider_cost_usd) })] }), _jsxs("div", { children: [_jsx("dt", { children: "Calculated" }), _jsx("dd", { children: money(event.calculated_cost_usd) })] }), _jsxs("div", { children: [_jsx("dt", { children: "Source" }), _jsx("dd", { children: event.cost_source || "—" })] }), _jsxs("div", { className: "api-log-cost-event__full", children: [_jsx("dt", { children: "Tokens" }), _jsxs("dd", { children: [fmt(event.prompt_tokens || 0), " in / ", fmt(event.completion_tokens || 0), " out", (event.cached_tokens || 0) > 0 ? ` · ${fmt(event.cached_tokens)} cached` : "", (event.reasoning_tokens || 0) > 0
                                                                        ? ` · ${fmt(event.reasoning_tokens)} reasoning`
                                                                        : ""] })] }), event.upstream_request_id && (_jsxs("div", { className: "api-log-cost-event__full", children: [_jsx("dt", { children: "Upstream ID" }), _jsx("dd", { children: _jsx("code", { className: "api-log-cost-event__id", children: event.upstream_request_id }) })] })), event.error_message && (_jsxs("div", { className: "api-log-cost-event__full", children: [_jsx("dt", { children: "Error" }), _jsx("dd", { children: event.error_message })] }))] }), event.line_items.length > 0 && (_jsx("div", { className: "api-log-cost-lines-wrap", children: _jsxs("table", { className: "api-log-cost-lines", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Category" }), _jsx("th", { children: "Qty" }), _jsx("th", { children: "Unit price" }), _jsx("th", { children: "Cost" }), _jsx("th", { children: "Pricing" })] }) }), _jsx("tbody", { children: event.line_items.map((line, idx) => (_jsxs("tr", { children: [_jsx("td", { children: line.category }), _jsxs("td", { children: [fmt(line.quantity), " ", line.unit] }), _jsx("td", { children: money(line.unit_price_usd) }), _jsx("td", { children: money(line.cost_usd) }), _jsx("td", { children: line.pricing_source || "—" })] }, `${event.id}-${line.category}-${idx}`))) })] }) }))] }, event.id));
                                })] })] }))] })) }));
}
