import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { isPromptQueueCollapsed, promptQueueCountLabel, shouldShowPromptQueueBar, } from "../../lib/promptQueue";
export default function PromptQueue({ items, expanded, onToggleExpanded, onEdit, onRemove, onClearAll, }) {
    if (!items.length)
        return null;
    const collapsed = isPromptQueueCollapsed({ count: items.length, expanded });
    const showBar = shouldShowPromptQueueBar(items.length);
    const nextPreview = items[0]?.preview ?? "";
    return (_jsxs("div", { className: "alpha-router-prompt-queue", "aria-label": "Queued messages", children: [showBar ? (_jsxs("div", { className: "alpha-router-prompt-queue__bar", children: [_jsx("span", { className: "alpha-router-prompt-queue__count", children: promptQueueCountLabel(items.length) }), collapsed ? (_jsxs("span", { className: "alpha-router-prompt-queue__next", title: nextPreview, children: ["Next: ", nextPreview] })) : (_jsx("span", { className: "alpha-router-prompt-queue__next", "aria-hidden": true })), _jsxs("div", { className: "alpha-router-prompt-queue__actions", children: [_jsx("button", { type: "button", className: "alpha-router-prompt-queue__btn alpha-router-prompt-queue__btn--text", onClick: onToggleExpanded, "aria-expanded": !collapsed, "aria-label": collapsed ? "Show queued messages" : "Hide queued messages", title: collapsed ? "Show queue" : "Hide queue", children: collapsed ? "Show" : "Hide" }), _jsx("button", { type: "button", className: "alpha-router-prompt-queue__btn alpha-router-prompt-queue__btn--text", onClick: onClearAll, "aria-label": "Clear queued messages", title: "Clear all", children: "Clear" })] })] })) : null, collapsed ? null : (_jsx("div", { className: "alpha-router-prompt-queue__list", children: items.map((item, idx) => (_jsxs("div", { className: "alpha-router-prompt-queue__item", children: [_jsx("span", { className: "alpha-router-prompt-queue__index", "aria-hidden": true, children: idx + 1 }), _jsx("span", { className: "alpha-router-prompt-queue__text", title: item.preview, children: item.preview }), _jsxs("div", { className: "alpha-router-prompt-queue__actions", children: [_jsx("button", { type: "button", className: "alpha-router-prompt-queue__btn", onClick: () => onEdit(item.id), "aria-label": "Edit queued message", title: "Edit", children: "\u270E" }), _jsx("button", { type: "button", className: "alpha-router-prompt-queue__btn alpha-router-prompt-queue__btn--remove", onClick: () => onRemove(item.id), "aria-label": "Remove from queue", title: "Remove", children: "\u00D7" })] })] }, item.id))) }))] }));
}
