"""Canonical persisted chat/media wire markers."""

IMAGE_MESSAGE_PREFIX = "__ALPHA_ROUTER_IMAGE_JSON__:"
IMAGE_PENDING_MARKER = "__ALPHA_ROUTER_IMAGE_PENDING__"
ATTACHMENT_MESSAGE_PREFIX = "__ALPHA_ROUTER_ATTACH_JSON__:"
AUDIO_MESSAGE_PREFIX = "__ALPHA_ROUTER_AUDIO_JSON__:"
