"""Predefined admin report catalog (30 reports)."""

from __future__ import annotations

from typing import Any, Literal

ParamKind = Literal[
    "user",
    "plan",
    "department",
    "office",
    "group",
    "nitro_api_key",
    "app",
    "model",
    "provider",
    "top_n",
    "threshold_pct",
    "latency_ms",
    "inactive_days",
    "auth_provider",
    "group_by",
]

REPORT_CATALOG: list[dict[str, Any]] = [
    # Budget & cost (1–7)
    {
        "id": "user_budget_usage",
        "category": "budget",
        "title": "User budget usage",
        "description": "Spend and request count per user in the selected period.",
        "needs_date": True,
        "params": ["user"],
    },
    {
        "id": "plan_usage",
        "category": "budget",
        "title": "Usage by plan",
        "description": "Spend per user covered by a budget plan (direct, group, or department assignment).",
        "needs_date": True,
        "params": ["plan"],
    },
    {
        "id": "org_cost_summary",
        "category": "budget",
        "title": "Organization cost summary",
        "description": "Total spend, requests, and tokens for the whole service.",
        "needs_date": True,
        "params": [],
    },
    {
        "id": "users_near_budget_limit",
        "category": "budget",
        "title": "Users near budget limit",
        "description": "Users at or above a percentage of their monthly budget (current period).",
        "needs_date": False,
        "params": ["threshold_pct"],
    },
    {
        "id": "users_without_budget",
        "category": "budget",
        "title": "Users without budget",
        "description": "Users with no effective monthly budget or explicit No Plan.",
        "needs_date": False,
        "params": [],
    },
    {
        "id": "department_top_models",
        "category": "budget",
        "title": "Department usage & top models",
        "description": "Top models by spend for users in a department.",
        "needs_date": True,
        "params": ["department"],
    },
    {
        "id": "office_usage",
        "category": "budget",
        "title": "Office usage",
        "description": "Spend and requests grouped by office.",
        "needs_date": True,
        "params": ["office"],
    },
    # Usage & models (8–15)
    {
        "id": "top_users_by_spend",
        "category": "usage",
        "title": "Top users by spend",
        "description": "Highest-spending users in the period.",
        "needs_date": True,
        "params": ["top_n"],
    },
    {
        "id": "top_models_by_spend",
        "category": "usage",
        "title": "Top models by spend",
        "description": "Highest-spending models in the period.",
        "needs_date": True,
        "params": ["top_n"],
    },
    {
        "id": "user_model_usage",
        "category": "usage",
        "title": "User usage by model",
        "description": "Spend, tokens, and requests per user and model.",
        "needs_date": True,
        "params": ["user"],
    },
    {
        "id": "usage_by_app",
        "category": "usage",
        "title": "Usage by application",
        "description": "Spend grouped by client application (Open WebUI, etc.).",
        "needs_date": True,
        "params": ["app"],
    },
    {
        "id": "usage_by_api_source",
        "category": "usage",
        "title": "Usage by API source",
        "description": "Spend grouped by gateway, NITRO key, or user key.",
        "needs_date": True,
        "params": [],
    },
    {
        "id": "usage_by_provider",
        "category": "usage",
        "title": "Usage by provider",
        "description": "Spend grouped by model provider (OpenAI, OpenRouter, …).",
        "needs_date": True,
        "params": ["provider"],
    },
    {
        "id": "token_breakdown",
        "category": "usage",
        "title": "Token breakdown",
        "description": "Prompt, completion, and cached tokens in the period.",
        "needs_date": True,
        "params": [],
    },
    {
        "id": "usage_by_prompt_language",
        "category": "usage",
        "title": "Usage by prompt language",
        "description": "Spend and requests grouped by detected prompt language.",
        "needs_date": True,
        "params": [],
    },
    # Operations (16–20)
    {
        "id": "model_error_rates",
        "category": "operations",
        "title": "Model error rates",
        "description": "Failed request percentage per model.",
        "needs_date": True,
        "params": ["model"],
    },
    {
        "id": "failed_requests",
        "category": "operations",
        "title": "Failed requests",
        "description": "Detailed list of unsuccessful API requests.",
        "needs_date": True,
        "params": ["user", "model"],
    },
    {
        "id": "slow_models_latency",
        "category": "operations",
        "title": "Slow models (latency)",
        "description": "Average and p95 response time per model.",
        "needs_date": True,
        "params": ["latency_ms"],
    },
    {
        "id": "slow_requests",
        "category": "operations",
        "title": "Slow requests",
        "description": "Individual requests slower than the threshold.",
        "needs_date": True,
        "params": ["latency_ms"],
    },
    {
        "id": "activity_summary",
        "category": "operations",
        "title": "Usage & activity summary",
        "description": "Spend, requests, and tokens grouped by model, app, or user.",
        "needs_date": True,
        "params": ["group_by"],
    },
    # Users & access (21–26)
    {
        "id": "deactivated_users",
        "category": "users",
        "title": "Deactivated users",
        "description": "Users marked Deactive with last login.",
        "needs_date": False,
        "params": [],
    },
    {
        "id": "users_no_recent_login",
        "category": "users",
        "title": "Users without recent login",
        "description": "Active users who have not signed in within N days.",
        "needs_date": True,
        "params": ["inactive_days"],
    },
    {
        "id": "new_users",
        "category": "users",
        "title": "New users",
        "description": "Accounts created in the selected period.",
        "needs_date": True,
        "params": [],
    },
    {
        "id": "deleted_users_report",
        "category": "users",
        "title": "Deleted users",
        "description": "Accounts soft-deleted in the selected period.",
        "needs_date": True,
        "params": [],
    },
    {
        "id": "auth_provider_distribution",
        "category": "users",
        "title": "Auth provider distribution",
        "description": "User counts by authentication source.",
        "needs_date": False,
        "params": [],
    },
    {
        "id": "users_without_group",
        "category": "users",
        "title": "Users without a group",
        "description": "Active users who are not members of any group.",
        "needs_date": False,
        "params": ["auth_provider"],
    },
    # Groups & API keys (27–30)
    {
        "id": "group_members_usage",
        "category": "groups",
        "title": "Group members usage",
        "description": "Per-member spend for a group in the period.",
        "needs_date": True,
        "params": ["group"],
    },
    {
        "id": "plan_assignments",
        "category": "groups",
        "title": "Plan assignments",
        "description": "Current budget plan assignments to users, groups, and departments.",
        "needs_date": False,
        "params": ["plan"],
    },
    {
        "id": "nitro_api_key_usage",
        "category": "api_keys",
        "title": "NITRO API key usage",
        "description": "Spend and requests per gateway API key.",
        "needs_date": True,
        "params": ["nitro_api_key"],
    },
    {
        "id": "nitro_api_keys_near_credit_limit",
        "category": "api_keys",
        "title": "API keys near credit limit",
        "description": "NITRO keys at or above 80% of their credit limit (current period).",
        "needs_date": False,
        "params": ["threshold_pct"],
    },
]

REPORT_IDS = frozenset(r["id"] for r in REPORT_CATALOG)

CATEGORY_LABELS = {
    "budget": "Budget & cost",
    "usage": "Usage & models",
    "operations": "Operations",
    "users": "Users & access",
    "groups": "Groups & plans",
    "api_keys": "API keys",
}
