"""add agent knowledge foundation

Revision ID: 31adeeec2bce
Revises: 
Create Date: 2026-08-12 11:52:38.243689
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '31adeeec2bce'
down_revision: Union[str, None] = "0000a1b2c3d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'leased', 'processed', 'retry', 'dead')", name='chk_outbox_events_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_outbox_events_idempotency')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_events_aggregate', ['aggregate_type', 'aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_aggregate_type'), ['aggregate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_available_at'), ['available_at'], unique=False)
        batch_op.create_index('ix_outbox_events_due', ['status', 'available_at', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_outbox_events_lease', ['lease_until', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_lease_owner'), ['lease_owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_lease_until'), ['lease_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_status'), ['status'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('access_type', sa.String(length=16), nullable=False),
    sa.Column('acl_version', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("access_type IN ('public', 'private')", name='chk_agents_access_type'),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name='chk_agents_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_access_type'), ['access_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_agents_status'), ['status'], unique=False)
        batch_op.create_index('ix_agents_status_sort', ['status', 'sort_order', 'name'], unique=False)

    op.create_table('deletion_tombstones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('vector_selector', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cache_selector', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='chk_deletion_tombstones_status'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', name='uq_deletion_tombstone_resource')
    )
    with op.batch_alter_table('deletion_tombstones', schema=None) as batch_op:
        batch_op.create_index('ix_deletion_tombstones_due', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_tombstones_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_tombstones_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_tombstones_status'), ['status'], unique=False)

    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('access_type', sa.String(length=16), nullable=False),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('acl_version', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_group_id', sa.Integer(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("access_type IN ('public', 'private')", name='chk_knowledge_bases_access_type'),
    sa.CheckConstraint("sensitivity IN ('internal', 'confidential', 'hr_confidential', 'legal_privileged', 'finance_restricted')", name='chk_knowledge_bases_sensitivity'),
    sa.CheckConstraint("status IN ('draft', 'active', 'suspended', 'archived')", name='chk_knowledge_bases_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_group_id'], ['user_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_bases_access_type'), ['access_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_owner_group_id'), ['owner_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_sensitivity'), ['sensitivity'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_status'), ['status'], unique=False)
        batch_op.create_index('ix_knowledge_bases_status_name', ['status', 'name'], unique=False)

    op.create_table('legal_holds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('placed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('released_by_user_id', sa.Integer(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'released')", name='chk_legal_holds_status'),
    sa.ForeignKeyConstraint(['placed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['released_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_holds_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index('ix_legal_holds_resource_status', ['resource_type', 'resource_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_holds_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_holds_status'), ['status'], unique=False)

    op.create_table('agent_access_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('role_slug', sa.String(length=64), nullable=True),
    sa.Column('effect', sa.String(length=8), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("effect IN ('allow', 'deny')", name='chk_agent_access_effect'),
    sa.CheckConstraint('((CASE WHEN user_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN group_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN department IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN role_slug IS NOT NULL THEN 1 ELSE 0 END)) = 1', name='chk_agent_access_one_target'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'department', 'effect', name='uq_agent_access_department_effect'),
    sa.UniqueConstraint('agent_id', 'group_id', 'effect', name='uq_agent_access_group_effect'),
    sa.UniqueConstraint('agent_id', 'role_slug', 'effect', name='uq_agent_access_role_effect'),
    sa.UniqueConstraint('agent_id', 'user_id', 'effect', name='uq_agent_access_user_effect')
    )
    with op.batch_alter_table('agent_access_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_agent_access_agent_effect', ['agent_id', 'effect'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_access_assignments_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_access_assignments_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_access_assignments_effect'), ['effect'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_access_assignments_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_access_assignments_role_slug'), ['role_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_access_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('agent_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tool_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('retrieval_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('memory_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('profile_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('routing_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('escalation_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('disclaimer_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('guardrail_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('locale_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('active_scope_key', sa.String(length=80), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('published_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'review', 'published', 'archived')", name='chk_agent_versions_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version_number', name='uq_agent_versions_number'),
    sa.UniqueConstraint('fingerprint', name='uq_agent_versions_fingerprint')
    )
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_versions_active_scope_key'), ['active_scope_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_versions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_agent_versions_agent_status', ['agent_id', 'status', 'version_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_published_by_user_id'), ['published_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_status'), ['status'], unique=False)

    op.create_table('knowledge_base_access_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('role_slug', sa.String(length=64), nullable=True),
    sa.Column('effect', sa.String(length=8), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("effect IN ('allow', 'deny')", name='chk_kb_access_effect'),
    sa.CheckConstraint('((CASE WHEN user_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN group_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN department IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN role_slug IS NOT NULL THEN 1 ELSE 0 END)) = 1', name='chk_kb_access_one_target'),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'department', 'effect', name='uq_kb_access_department_effect'),
    sa.UniqueConstraint('knowledge_base_id', 'group_id', 'effect', name='uq_kb_access_group_effect'),
    sa.UniqueConstraint('knowledge_base_id', 'role_slug', 'effect', name='uq_kb_access_role_effect'),
    sa.UniqueConstraint('knowledge_base_id', 'user_id', 'effect', name='uq_kb_access_user_effect')
    )
    with op.batch_alter_table('knowledge_base_access_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_kb_access_resource_effect', ['knowledge_base_id', 'effect'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_access_assignments_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_access_assignments_effect'), ['effect'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_access_assignments_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_access_assignments_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_access_assignments_role_slug'), ['role_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_access_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('checkpoint_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'paused', 'failed', 'archived')", name='chk_knowledge_connectors_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'name', name='uq_knowledge_connectors_name')
    )
    with op.batch_alter_table('knowledge_connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_connectors_connector_type'), ['connector_type'], unique=False)
        batch_op.create_index('ix_knowledge_connectors_kb_status', ['knowledge_base_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connectors_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connectors_last_synced_at'), ['last_synced_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connectors_status'), ['status'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_key', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('acl_version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'superseded', 'revoked', 'deleted')", name='chk_knowledge_documents_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'canonical_key', name='uq_knowledge_document_canonical_key')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_knowledge_documents_kb_status', ['knowledge_base_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_status'), ['status'], unique=False)

    op.create_table('knowledge_releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('active_scope_key', sa.String(length=80), nullable=True),
    sa.Column('manifest_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('published_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'indexing', 'review', 'published', 'archived', 'failed')", name='chk_knowledge_releases_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_knowledge_releases_fingerprint'),
    sa.UniqueConstraint('knowledge_base_id', 'version_number', name='uq_knowledge_releases_number')
    )
    with op.batch_alter_table('knowledge_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_releases_active_scope_key'), ['active_scope_key'], unique=True)
        batch_op.create_index('ix_knowledge_releases_kb_status', ['knowledge_base_id', 'status', 'version_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_releases_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_releases_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_releases_status'), ['status'], unique=False)

    op.create_table('agent_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('agent_version_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_agent_audit_actor_time', ['actor_user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_agent_audit_agent_time', ['agent_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_audit_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_audit_events_agent_version_id'), ['agent_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('agent_handoff_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('from_agent_id', sa.String(length=36), nullable=True),
    sa.Column('to_agent_id', sa.String(length=36), nullable=True),
    sa.Column('from_agent_version_id', sa.String(length=36), nullable=True),
    sa.Column('to_agent_version_id', sa.String(length=36), nullable=True),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('consent_required', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('proposed', 'accepted', 'declined', 'completed', 'failed')", name='chk_agent_handoff_status'),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_agent_version_id'], ['agent_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_agent_version_id'], ['agent_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_handoff_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_handoff_events_from_agent_id'), ['from_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_handoff_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_handoff_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_handoff_events_to_agent_id'), ['to_agent_id'], unique=False)
        batch_op.create_index('ix_agent_handoff_session_time', ['session_id', 'created_at'], unique=False)

    op.create_table('agent_knowledge_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_version_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('release_mode', sa.String(length=16), nullable=False),
    sa.Column('pinned_release_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retrieval_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('kb_approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('domain_approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('kb_approved_at', sa.DateTime(), nullable=True),
    sa.Column('domain_approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("release_mode IN ('latest', 'pinned')", name='chk_agent_knowledge_release_mode'),
    sa.CheckConstraint("status IN ('draft', 'pending_kb_approval', 'pending_domain_approval', 'approved', 'published', 'suspended', 'revoked')", name='chk_agent_knowledge_binding_status'),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kb_approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_release_id'], ['knowledge_releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_version_id', 'knowledge_base_id', name='uq_agent_knowledge_binding')
    )
    with op.batch_alter_table('agent_knowledge_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_knowledge_bindings_agent_version_id'), ['agent_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_knowledge_bindings_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_knowledge_bindings_pinned_release_id'), ['pinned_release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_knowledge_bindings_status'), ['status'], unique=False)

    op.create_table('connector_sync_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('discovered_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('deleted_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('checkpoint_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'partial', 'failed', 'cancelled')", name='chk_connector_sync_runs_status'),
    sa.ForeignKeyConstraint(['connector_id'], ['knowledge_connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector_sync_runs', schema=None) as batch_op:
        batch_op.create_index('ix_connector_sync_connector_time', ['connector_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_sync_runs_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_sync_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_sync_runs_status'), ['status'], unique=False)

    op.create_table('knowledge_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('release_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['knowledge_releases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_audit_actor_time', ['actor_user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_audit_events_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_audit_events_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_audit_events_release_id'), ['release_id'], unique=False)
        batch_op.create_index('ix_knowledge_audit_kb_time', ['knowledge_base_id', 'created_at'], unique=False)

    op.create_table('knowledge_document_access_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('role_slug', sa.String(length=64), nullable=True),
    sa.Column('effect', sa.String(length=8), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("effect IN ('allow', 'deny')", name='chk_knowledge_document_access_effect'),
    sa.CheckConstraint('((CASE WHEN user_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN group_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN department IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN role_slug IS NOT NULL THEN 1 ELSE 0 END)) = 1', name='chk_knowledge_document_access_one_target'),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'department', 'effect', name='uq_knowledge_document_access_department_effect'),
    sa.UniqueConstraint('document_id', 'group_id', 'effect', name='uq_knowledge_document_access_group_effect'),
    sa.UniqueConstraint('document_id', 'role_slug', 'effect', name='uq_knowledge_document_access_role_effect'),
    sa.UniqueConstraint('document_id', 'user_id', 'effect', name='uq_knowledge_document_access_user_effect')
    )
    with op.batch_alter_table('knowledge_document_access_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_document_access_resource_effect', ['document_id', 'effect'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_access_assignments_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_access_assignments_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_access_assignments_effect'), ['effect'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_access_assignments_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_access_assignments_role_slug'), ['role_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_access_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('active_scope_key', sa.String(length=80), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('authority', sa.String(length=32), nullable=False),
    sa.Column('jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('review_due_at', sa.DateTime(), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('uploaded', 'quarantined', 'processing', 'review', 'published', 'superseded', 'revoked', 'failed')", name='chk_knowledge_document_versions_status'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_knowledge_document_versions_number'),
    sa.UniqueConstraint('sha256', 'document_id', name='uq_document_version_hash'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('knowledge_document_versions', schema=None) as batch_op:
        batch_op.create_index('ix_document_versions_document_status', ['document_id', 'status', 'version_number'], unique=False)
        batch_op.create_index('ix_document_versions_effective', ['effective_from', 'effective_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_active_scope_key'), ['active_scope_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_authority'), ['authority'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_effective_to'), ['effective_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_jurisdiction'), ['jurisdiction'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_review_due_at'), ['review_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_document_versions_uploaded_by_user_id'), ['uploaded_by_user_id'], unique=False)

    op.create_table('knowledge_index_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('embedding_provider', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=512), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('sparse_profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('chunker_version', sa.String(length=64), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('collection_alias', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('active_scope_key', sa.String(length=80), nullable=True),
    sa.Column('expected_point_count', sa.Integer(), nullable=False),
    sa.Column('indexed_point_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('planned', 'building', 'validating', 'active', 'retired', 'failed')", name='chk_knowledge_index_versions_status'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['knowledge_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_name'),
    sa.UniqueConstraint('fingerprint', name='uq_knowledge_index_versions_fingerprint'),
    sa.UniqueConstraint('knowledge_base_id', 'version_number', name='uq_knowledge_index_versions_number')
    )
    with op.batch_alter_table('knowledge_index_versions', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_index_kb_status', ['knowledge_base_id', 'status', 'version_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_index_versions_activated_at'), ['activated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_index_versions_active_scope_key'), ['active_scope_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_index_versions_collection_alias'), ['collection_alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_index_versions_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_index_versions_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_index_versions_status'), ['status'], unique=False)

    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=True),
    sa.Column('index_version_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'leased', 'processing', 'retry', 'succeeded', 'dead', 'cancelled')", name='chk_ingestion_jobs_status'),
    sa.ForeignKeyConstraint(['document_version_id'], ['knowledge_document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['index_version_id'], ['knowledge_index_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_ingestion_jobs_idempotency')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index('ix_ingestion_jobs_due', ['status', 'next_attempt_at', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_index_version_id'), ['index_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_index('ix_ingestion_jobs_lease', ['lease_until', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_lease_owner'), ['lease_owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_lease_until'), ['lease_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_status'), ['status'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('parent_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['knowledge_document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['knowledge_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'chunk_index', name='uq_knowledge_chunks_index'),
    sa.UniqueConstraint('document_version_id', 'content_hash', name='uq_knowledge_chunks_hash')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index('ix_knowledge_chunks_document_page', ['document_version_id', 'page_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_parent_chunk_id'), ['parent_chunk_id'], unique=False)

    op.create_table('knowledge_release_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['knowledge_document_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['release_id'], ['knowledge_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_id', 'document_version_id', name='uq_knowledge_release_document')
    )
    with op.batch_alter_table('knowledge_release_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_release_documents_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_release_documents_release_id'), ['release_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_release_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_release_documents_release_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_release_documents_document_version_id'))

    op.drop_table('knowledge_release_documents')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_parent_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_language'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_version_id'))
        batch_op.drop_index('ix_knowledge_chunks_document_page')
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_content_hash'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_lease_until'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_lease_owner'))
        batch_op.drop_index('ix_ingestion_jobs_lease')
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_knowledge_base_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_index_version_id'))
        batch_op.drop_index('ix_ingestion_jobs_due')
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_document_version_id'))

    op.drop_table('ingestion_jobs')
    with op.batch_alter_table('knowledge_index_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_index_versions_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_index_versions_release_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_index_versions_knowledge_base_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_index_versions_collection_alias'))
        batch_op.drop_index(batch_op.f('ix_knowledge_index_versions_active_scope_key'))
        batch_op.drop_index(batch_op.f('ix_knowledge_index_versions_activated_at'))
        batch_op.drop_index('ix_knowledge_index_kb_status')

    op.drop_table('knowledge_index_versions')
    with op.batch_alter_table('knowledge_document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_uploaded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_source_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_sha256'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_review_due_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_published_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_language'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_jurisdiction'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_effective_to'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_effective_from'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_document_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_classification'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_authority'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_versions_active_scope_key'))
        batch_op.drop_index('ix_document_versions_effective')
        batch_op.drop_index('ix_document_versions_document_status')

    op.drop_table('knowledge_document_versions')
    with op.batch_alter_table('knowledge_document_access_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_document_access_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_access_assignments_role_slug'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_access_assignments_group_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_access_assignments_effect'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_access_assignments_document_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_document_access_assignments_department'))
        batch_op.drop_index('ix_document_access_resource_effect')

    op.drop_table('knowledge_document_access_assignments')
    with op.batch_alter_table('knowledge_audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_audit_kb_time')
        batch_op.drop_index(batch_op.f('ix_knowledge_audit_events_release_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_audit_events_knowledge_base_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_audit_events_document_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_audit_events_actor_user_id'))
        batch_op.drop_index('ix_knowledge_audit_actor_time')

    op.drop_table('knowledge_audit_events')
    with op.batch_alter_table('connector_sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_sync_runs_status'))
        batch_op.drop_index(batch_op.f('ix_connector_sync_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_connector_sync_runs_connector_id'))
        batch_op.drop_index('ix_connector_sync_connector_time')

    op.drop_table('connector_sync_runs')
    with op.batch_alter_table('agent_knowledge_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_knowledge_bindings_status'))
        batch_op.drop_index(batch_op.f('ix_agent_knowledge_bindings_pinned_release_id'))
        batch_op.drop_index(batch_op.f('ix_agent_knowledge_bindings_knowledge_base_id'))
        batch_op.drop_index(batch_op.f('ix_agent_knowledge_bindings_agent_version_id'))

    op.drop_table('agent_knowledge_bindings')
    with op.batch_alter_table('agent_handoff_events', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_handoff_session_time')
        batch_op.drop_index(batch_op.f('ix_agent_handoff_events_to_agent_id'))
        batch_op.drop_index(batch_op.f('ix_agent_handoff_events_status'))
        batch_op.drop_index(batch_op.f('ix_agent_handoff_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_handoff_events_from_agent_id'))

    op.drop_table('agent_handoff_events')
    with op.batch_alter_table('agent_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_agent_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_audit_events_agent_version_id'))
        batch_op.drop_index(batch_op.f('ix_agent_audit_events_agent_id'))
        batch_op.drop_index(batch_op.f('ix_agent_audit_events_actor_user_id'))
        batch_op.drop_index('ix_agent_audit_agent_time')
        batch_op.drop_index('ix_agent_audit_actor_time')

    op.drop_table('agent_audit_events')
    with op.batch_alter_table('knowledge_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_releases_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_releases_published_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_releases_knowledge_base_id'))
        batch_op.drop_index('ix_knowledge_releases_kb_status')
        batch_op.drop_index(batch_op.f('ix_knowledge_releases_active_scope_key'))

    op.drop_table('knowledge_releases')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_knowledge_base_id'))
        batch_op.drop_index('ix_knowledge_documents_kb_status')
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_deleted_at'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('knowledge_connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_connectors_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connectors_last_synced_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connectors_knowledge_base_id'))
        batch_op.drop_index('ix_knowledge_connectors_kb_status')
        batch_op.drop_index(batch_op.f('ix_knowledge_connectors_connector_type'))

    op.drop_table('knowledge_connectors')
    with op.batch_alter_table('knowledge_base_access_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_base_access_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_base_access_assignments_role_slug'))
        batch_op.drop_index(batch_op.f('ix_knowledge_base_access_assignments_knowledge_base_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_base_access_assignments_group_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_base_access_assignments_effect'))
        batch_op.drop_index(batch_op.f('ix_knowledge_base_access_assignments_department'))
        batch_op.drop_index('ix_kb_access_resource_effect')

    op.drop_table('knowledge_base_access_assignments')
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_versions_status'))
        batch_op.drop_index(batch_op.f('ix_agent_versions_published_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_versions_published_at'))
        batch_op.drop_index(batch_op.f('ix_agent_versions_created_by_user_id'))
        batch_op.drop_index('ix_agent_versions_agent_status')
        batch_op.drop_index(batch_op.f('ix_agent_versions_agent_id'))
        batch_op.drop_index(batch_op.f('ix_agent_versions_active_scope_key'))

    op.drop_table('agent_versions')
    with op.batch_alter_table('agent_access_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_access_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_access_assignments_role_slug'))
        batch_op.drop_index(batch_op.f('ix_agent_access_assignments_group_id'))
        batch_op.drop_index(batch_op.f('ix_agent_access_assignments_effect'))
        batch_op.drop_index(batch_op.f('ix_agent_access_assignments_department'))
        batch_op.drop_index(batch_op.f('ix_agent_access_assignments_agent_id'))
        batch_op.drop_index('ix_agent_access_agent_effect')

    op.drop_table('agent_access_assignments')
    with op.batch_alter_table('legal_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_holds_status'))
        batch_op.drop_index(batch_op.f('ix_legal_holds_resource_type'))
        batch_op.drop_index('ix_legal_holds_resource_status')
        batch_op.drop_index(batch_op.f('ix_legal_holds_resource_id'))

    op.drop_table('legal_holds')
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_bases_status_name')
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_slug'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_sensitivity'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_owner_group_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_access_type'))

    op.drop_table('knowledge_bases')
    with op.batch_alter_table('deletion_tombstones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deletion_tombstones_status'))
        batch_op.drop_index(batch_op.f('ix_deletion_tombstones_resource_type'))
        batch_op.drop_index(batch_op.f('ix_deletion_tombstones_resource_id'))
        batch_op.drop_index('ix_deletion_tombstones_due')

    op.drop_table('deletion_tombstones')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index('ix_agents_status_sort')
        batch_op.drop_index(batch_op.f('ix_agents_status'))
        batch_op.drop_index(batch_op.f('ix_agents_slug'))
        batch_op.drop_index(batch_op.f('ix_agents_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_agents_category'))
        batch_op.drop_index(batch_op.f('ix_agents_access_type'))

    op.drop_table('agents')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_lease_until'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_lease_owner'))
        batch_op.drop_index('ix_outbox_events_lease')
        batch_op.drop_index(batch_op.f('ix_outbox_events_event_type'))
        batch_op.drop_index('ix_outbox_events_due')
        batch_op.drop_index(batch_op.f('ix_outbox_events_available_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_aggregate_type'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_aggregate_id'))
        batch_op.drop_index('ix_outbox_events_aggregate')

    op.drop_table('outbox_events')
    # ### end Alembic commands ###
