#!/usr/bin/env bash
# Detect host docker.sock group id and write docker-compose.override.yml.

OVERRIDE_FILE="$ROOT_DIR/docker-compose.override.yml"

detect_docker_sock_gid() {
  local sock="${DOCKER_SOCK:-/var/run/docker.sock}"
  local gid=""

  if [ -e "$sock" ]; then
    if gid="$(stat -c '%g' "$sock" 2>/dev/null)"; then
      printf '%s' "$gid"
      return 0
    fi
    if gid="$(stat -f '%g' "$sock" 2>/dev/null)"; then
      printf '%s' "$gid"
      return 0
    fi
  fi

  if command -v getent >/dev/null 2>&1; then
    gid="$(getent group docker 2>/dev/null | awk -F: '{print $3}' || true)"
    if [ -n "$gid" ]; then
      printf '%s' "$gid"
      return 0
    fi
  fi

  return 1
}

write_docker_compose_override() {
  local gid
  gid="$(detect_docker_sock_gid)" || die "Could not detect docker.sock group id."

  log "Docker socket group id: $gid"

  cat >"$OVERRIDE_FILE" <<EOF
# Generated by scripts/install.sh — re-run install to refresh after host changes.
services:
  alpha-router-sandbox-broker:
    group_add:
      - "$gid"
EOF

  log "Wrote $OVERRIDE_FILE"
}
