"""Canonical product identity shared across backend surfaces."""

PRODUCT_NAME = "Alpha Router"
PRODUCT_TOKEN = "AlphaRouter"
PRODUCT_SLUG = "alpha-router"
PRODUCT_SNAKE = "alpha_router"

APPLICATION_TITLE = f"{PRODUCT_NAME} Organizational AI Platform"
CHAT_CLIENT_APP = f"{PRODUCT_NAME} Chat"
INTERNAL_DOMAIN = f"{PRODUCT_SLUG}.local"
LOGGER_NAMESPACE = PRODUCT_SNAKE
OUTBOUND_USER_AGENT = f"{PRODUCT_TOKEN}/1.0 (+https://{INTERNAL_DOMAIN})"

SESSION_COOKIE_NAME = f"{PRODUCT_SNAKE}_session"
CSRF_COOKIE_NAME = f"{PRODUCT_SNAKE}_csrf"
OIDC_STATE_COOKIE_NAME = f"{PRODUCT_SNAKE}_oidc_state"
CONNECTOR_STATE_COOKIE_NAME = f"{PRODUCT_SNAKE}_connector_state"

API_KEY_PREFIX = f"{PRODUCT_SNAKE}_"
GATEWAY_MASTER_KEY_PREFIX = f"sk-{PRODUCT_SLUG}-"
GATEWAY_MASTER_KEY_DEFAULT = f"{GATEWAY_MASTER_KEY_PREFIX}master"

REPLACE_MESSAGES_HEADER = "X-Alpha Router-Router-Replace-Messages"
