#!/usr/bin/env python3
"""Conventional Commits check for the commit-msg hook (no Node dependency).

Accepted subject line:

    <type>(<scope>)?(!)?: <description>

types: build chore ci docs feat fix perf refactor revert style test
The description starts lowercase or with a symbol/identifier, has no trailing
period, and the whole subject is at most 100 characters. Merge and revert
commits generated by git, and fixup!/squash! prefixes, are accepted as-is.

Usage: check-commit-message.py <path-to-COMMIT_EDITMSG>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

TYPES = ("build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test")
SUBJECT_RE = re.compile(
    r"^(?P<type>" + "|".join(TYPES) + r")"
    r"(\((?P<scope>[a-z0-9][a-z0-9._/-]*)\))?"
    r"(?P<bang>!)?: "
    r"(?P<desc>\S.*)$"
)
MAX_SUBJECT = 100


def check(message: str) -> list[str]:
    lines = [line for line in message.splitlines() if not line.startswith("#")]
    subject = next((line for line in lines if line.strip()), "")
    if not subject:
        return ["empty commit message"]
    if subject.startswith(("Merge ", "Revert ", "fixup! ", "squash! ")):
        return []
    problems: list[str] = []
    if len(subject) > MAX_SUBJECT:
        problems.append(f"subject is {len(subject)} characters; keep it under {MAX_SUBJECT}")
    match = SUBJECT_RE.match(subject)
    if not match:
        problems.append(
            "subject must look like `type(scope): description` with type in " + ", ".join(TYPES)
        )
        return problems
    desc = match.group("desc")
    if desc.endswith("."):
        problems.append("description must not end with a period")
    if desc[0].isalpha() and desc[0].isupper() and not desc.split()[0].isupper():
        # "Redis" / "SAML" style proper nouns are fine; "Fix the thing" is not.
        problems.append("description starts lowercase (`fix: add ...`, not `fix: Add ...`)")
    body = lines[1:]
    if body and body[0].strip():
        problems.append("leave one blank line between the subject and the body")
    return problems


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print(__doc__)
        return 2
    message = Path(argv[0]).read_text(encoding="utf-8", errors="replace")
    problems = check(message)
    if not problems:
        return 0
    print("Commit message rejected:")
    for problem in problems:
        print(f"  - {problem}")
    print("\nSee CONTRIBUTING.md (Conventional Commits).")
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
